"""Create Init Tables

Revision ID: 3c2136baa51d
Revises: e13735b2acd6
Create Date: 2024-10-26 23:00:12.660526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c2136baa51d'
down_revision: Union[str, None] = 'e13735b2acd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distributor_user_id', sa.Integer(), nullable=False, comment='配布者'),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False, comment='受信者'),
    sa.Column('content', sa.String(length=500), nullable=True, comment='内容'),
    sa.Column('deadline_at', sa.Date(), nullable=True, comment='期限日'),
    sa.Column('completed_at', sa.Date(), nullable=True, comment='完了日'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.Column('is_deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_distributor_user_id'), 'task', ['distributor_user_id'], unique=False)
    op.create_index(op.f('ix_task_recipient_user_id'), 'task', ['recipient_user_id'], unique=False)
    op.create_table('task_action_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='実行者'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='タスク'),
    sa.Column('action_type', sa.Enum('UPDATE', 'DELETE', name='actiontype'), nullable=True, comment='内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_action_log_task_id'), 'task_action_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_action_log_user_id'), 'task_action_log', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='削除フラグ'))
    op.drop_index('ix_user_is_active', table_name='user')
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='アクティブ'))
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.create_index('ix_user_is_active', 'user', ['is_active'], unique=False)
    op.drop_column('user', 'is_deleted')
    op.drop_index(op.f('ix_task_action_log_user_id'), table_name='task_action_log')
    op.drop_index(op.f('ix_task_action_log_task_id'), table_name='task_action_log')
    op.drop_table('task_action_log')
    op.drop_index(op.f('ix_task_recipient_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_distributor_user_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
